spring:
  application:
    name: FirstSpring

first-spring:

---
spring:
  profiles:
    active: develop
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:hsqldb:mem:db/mp;hsqldb.log_data=true
    password:
    username: sa
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

---
spring:
  profiles:
    active: test

---
spring:
  profiles:
    active: uat

---
spring:
  profiles:
    active: prod